---
- name: Register and Enable Repos on OCP 3.11 Nodes
  hosts: "{{ target_host_name }}*"
  gather_facts: no

  tasks:
  - name: Update hostname
    hostname:
      # The variable name is sourced from dynamic inventory variable
      name: "{{ name }}"
    
  - name: Register and attach RHEL Subscription Pool ID
    redhat_subscription:
      state: present
      # Get these values from Survey
      username: "{{ redhat_user }}"
      password: "{{ redhat_pass }}"
      pool_ids: "{{ redhat_poolid }}"

  - name: disable all repos
    rhsm_repository:
      name: '*'
      state: disabled

  - name: enable rhel-7-server, rhel-7-server-extras, rhel-7-server-ose-3.11, rhel-7-server-ansible-2.6 repos
    rhsm_repository:
      name: 'rhel-7-server-rpms'
      state: enabled
    with_items:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-3.11-rpms
      - rhel-7-server-ansible-2.6-rpms
...