---
- name: Create OCP 3.11 Demo Cluster on RHV
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Creates Bastion Host
    ovirt_vm:
      state: present
      name: ocp311-bastion.internal.pineview.co.nz
      template: tmp_ocp_rhel76_master_20190227
      cluster: Pineview-Cluster-OCP
      description: OCP 3.11 Bastion Host
      comment: OCP 3.11
      cloud_init:
        nic_name: eth0
        nic_boot_protocol: static
        nic_ip_address: 10.68.158.80
        nic_netmask: 255.255.255.0
        nic_gateway: 10.68.158.254
        nic_on_boot: true
        dns_servers: 10.68.158.11 10.68.158.12
        dns_search: internal.pineview.co.nz

  - name: Power Up VM if needed
    ovirt_vm:
      state: running
      name: ocp311-bastion.internal.pineview.co.nz
      cluster: Pineview-Cluster-OCP
      wait: no
...
