---
- name: Create OCP 3.11 Demo Cluster on RHV
  hosts: localhost
  connection: local
  gather_facts: no

  # Get these vars from Survey:
  # - rhv_domain_name, rhv_cluster_name
  # - rhv_node_template_name, rhv_rhel_template_name

  tasks:
  - name: Creates OCP 3.11 Bastion and LB Hosts
    ovirt_vm:
      state: present
      name: "{{ item }}" 
      template: "{{ rhv_rhel_template_name }}"
      cluster: "{{ rhv_cluster_name }}"
      comment: OCP 3.11
    with_items:
      - ocp311-bastion.{{ rhv_domain_name }}
      - ocp311-lb.{{ rhv_domain_name }}

  - name: Creates OCP 3.11 Master, Infra, and Worker Nodes
    ovirt_vm:
      state: present
      name: "{{ item }}" 
      template: "{{ rhv_node_template_name }}"
      cluster: "{{ rhv_cluster_name }}"
      comment: OCP 3.11
    with_items:
      - ocp311-master1.{{ rhv_domain_name }}
      - ocp311-master2.{{ rhv_domain_name }}

  - name: Power Up All OCP VMs 
    ovirt_vm:
      state: running
      name: "{{ item }}"
      cluster: "{{ rhv_cluster_name }}"
      wait: no
    with_items:
      - ocp311-bastion.{{ rhv_domain_name }}
      - ocp311-lb.{{ rhv_domain_name }}
      - ocp311-master1.{{ rhv_domain_name }}
      - ocp311-master2.{{ rhv_domain_name }}
...
